
FROM ardupilot:latest

ARG DEBIAN_FRONTEND=noninteractive
ONBUILD ARG DEBIAN_FRONTEND=noninteractive
ARG LINK_RPI=https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Bullseye/GCC%2010.3.0/Raspberry%20Pi%201%2C%20Zero/cross-gcc-10.3.0-pi_0-1.tar.gz/download
# ARG LINK_RPI = https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Bullseye/GCC%2010.3.0/Raspberry%20Pi%202%2C%203/cross-gcc-10.3.0-pi_2-3.tar.gz/download
# ARG LINK_RPI = https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Bullseye/GCC%2010.3.0/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/cross-gcc-10.3.0-pi_3%2B.tar.gz/download

USER root

RUN cd /opt  \
    && wget -O cross-gcc-10.3.0-pi_0-1.tar.gz $LINK_RPI \
    && tar -xf cross-gcc-10.3.0-pi_0-1.tar.gz -C /opt \
    && rm -rf cross-gcc-10.3.0-pi_0-1.tar.gz \
    && rm -rf /usr/lib/ccache \
    && rm -rf /opt/gcc-arm-none-eabi-10-2020-q4-major

ENV PATH="/opt/cross-pi-gcc-10.3.0-1/bin:$PATH"
RUN echo "export PATH=$PATH" > /etc/environment
USER ardupilot

CMD ["/bin/bash"]